[package]
name = "ontool-bin"
version = "0.1.0"
edition = "2021"

[dependencies]
ontool.path = "../ontool"
tokio = { workspace = true, features = ["full"] }

[[bin]]
name = "ontool"
path = "src/main.rs"
