[package]
name = "ontol-runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false

[dependencies]
smartstring.workspace = true
tracing.workspace = true
indexmap.workspace = true
serde.workspace = true
serde_json.workspace = true
fnv.workspace = true
smallvec = "1"
num = "0.4"
serde-value = "0.7"
derive-debug-extras = { version = "0.2", features = ["auto-debug-single-tuple-inline"] }
time = { version = "0.3", features = ["serde-well-known"] }
chrono = { version = "0.4" , features = ["serde"] }
uuid = "1"
regex = "1"
bitflags = "2"

[dev-dependencies]
tracing-subscriber = {version = "0.3", default-features = false, features = ["env-filter", "fmt"]}
test-log = { version = "0.2", default-features = false, features = ["trace"] }
