[package]
name = "ontol-runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smartstring = { version = "1", features = ["serde"] }
indexmap = "1"
serde = "1"
serde_json = "1"
derive-debug-extras = { version = "0.2", features = ["auto-debug-single-tuple-inline"] }
