[package]
name = "ontol-macros"
version = "0.1.0"
authors = ["Audun Halland <audun.halland@pm.me>"]
edition = "2021"

[dependencies]
syn = { version = "2.0.14", features = ["full", "visit-mut"] }
quote = "1"
proc-macro2 = "1"

[lib]
proc-macro = true
