[package]
name = "ontol-lsp"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Remove for production
console_error_panic_hook = { version = "0.1.6", optional = true }
ontol-runtime.path = "../ontol-runtime"
ontol-compiler.path = "../ontol-compiler"
lsp-types = "0.94.0"
wasm-bindgen = "0.2.84"
wasm-bindgen-futures = { version = "0.4.34", features = ["futures-core-03-stream"] }

[dependencies.tower-lsp]
version = "0.19.0"
default-features = false
features = [
    "runtime-agnostic"
]

[dependencies.web-sys]
version = "0.3.61"
features = [
    "console",
    "ReadableStream",
    "WritableStream",
]

[profile.release]
lto = true
opt-level = "s"
# opt-level = "z"
