[package]
name = "ontol-lsp"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
ontol-runtime.path = "../ontol-runtime"
ontol-compiler.path = "../ontol-compiler"
ontol-parser.path = "../ontol-parser"
chumsky = "0.9"
lsp-types = "0.94.0"
tokio = { workspace = true, features = ["full"] }
tower-lsp = "0.19.0"
substring = "1.4.5"
regex = "1.9.1"
