stages:
  - check

lint:
  stage: check
  image: rust:latest
  script:
    - rustup component add rustfmt clippy
    - cargo fmt -- --check
    - cargo clippy

test:
  stage: check
  image: rust:latest
  script:
    - cargo test
