variables:
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
  DOMAIN_ENGINE_SKIP_ARANGO_TEST: 1

stages:
  - check

lint:
  stage: check
  image: rust:latest
  script:
    - rustup component add rustfmt clippy
    - cargo fmt -- --check
    - cargo clippy --all-targets -- -D warnings

test:
  stage: check
  image: rust:latest
  script:
    - cargo test --tests --benches --no-fail-fast
