variables:
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

stages:
  - check

lint:
  stage: check
  image: rust:latest
  script:
    - rustup component add rustfmt clippy
    - cargo fmt -- --check
    - cargo clippy -- -D warnings

test:
  stage: check
  image: rust:latest
  script:
    - cargo test

test-wasm:
  stage: check
  image: rust:latest
  script:
    - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - cd domain-engine-wasm/
    - wasm-pack build --target web
