stages:
  - check

pretty:
  stage: check
  image: rust:latest
  script:
    - rustup component add rustfmt
    - cargo fmt -- --check

test:
  stage: check
  image: rust:latest
  script:
    - cargo test
