variables:
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

stages:
  - check

lint:
  stage: check
  image: rust:latest
  script:
    - rustup component add rustfmt clippy
    - cargo fmt -- --check
    - cargo clippy -- -D warnings

test:
  stage: check
  image: rust:latest
  script:
    - cargo test
    - cargo test --bench '*'
