[workspace]

members = [
    "domain-engine-core",
    "domain-engine-juniper",
    "domain-engine-wasm",
    "ontol-runtime",
    "ontol-compiler",
    "ontol-parser",
    "ontol-test-utils"
]

# Set the settings for build scripts and proc-macros.
[profile.release.package.domain-engine-wasm]
opt-level = "s"
