[workspace]
members = [
    "domain-engine-core",
    "domain-engine-juniper",
    "domain-engine-wasm",
    "ontol-faker",
    "ontol-hir",
    "ontol-runtime",
    "ontol-compiler",
    "ontol-parser",
    "ontol-test-utils",
    "ontol-lsp",
    "ontool",
]

[workspace.dependencies]
fnv = "1"
indexmap = "2"
serde = "1"
serde_json = "1"
serde_yaml = "0.9"
smartstring = { version = "1", features = ["serde"] }
smallvec = "1"
itertools = "0.11"
uuid = "1"
tokio = { version = "1", features = ["macros", "rt"] }
async-trait = "0.1"
test-log = { version = "0.2", default-features = false, features = ["trace"] }
thiserror = "1"
tracing = "0.1"
tracing-subscriber = {version = "0.3", default-features = false, features = ["env-filter", "fmt", "ansi"]}
