[workspace]
members = [
    "domain-engine-core",
    "domain-engine-juniper",
    "domain-engine-wasm",
    "ontol-faker",
    "ontol-hir",
    "ontol-runtime",
    "ontol-compiler",
    "ontol-parser",
    "ontol-cli",
    "ontol-test-utils"
]

[workspace.dependencies]
fnv = "1"
indexmap = "1"
serde = "1"
serde_json = "1"
serde_yaml = "0.9"
smallvec = "1"
smartstring = { version = "1", features = ["serde"] }
test-log = { version = "0.2", default-features = false, features = ["trace"] }
thiserror = "1"
tracing = "0.1"
tracing-subscriber = {version = "0.3", default-features = false, features = ["env-filter", "fmt"]}

# Set the settings for build scripts and proc-macros.
[profile.release.package.domain-engine-wasm]
opt-level = "s"
