[package]
name = "ontol-macros"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
syn = { version = "2.0.14", features = ["full", "visit-mut"] }
quote = "1"
proc-macro2 = "1"
unindent = "0.2"

[lib]
proc-macro = true
