[package]
name = "ontol-log"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
ontol-core.path = "../ontol-core"
ontol-macros.path = "../ontol-macros"
ontol-parser.path = "../ontol-parser"
ontol-syntax.path = "../ontol-syntax"
arcstr.workspace = true
async-trait.workspace = true
bit-set.workspace = true
bitflags.workspace = true
displaydoc = "0.2"
either = "1"
fnv.workspace = true
hex = "0.4"
indexmap.workspace = true
indoc = "2"
itertools.workspace = true
pest = "2"
pest_derive = "2"
rustc-hash = "2"
serde.workspace = true
smallvec.workspace = true
thiserror.workspace = true
tracing.workspace = true
thin-vec.workspace = true
ulid = { version = "1", features = ["serde"] }
unsigned-varint = "0.8"
url = "2"

[dev-dependencies]
#ontol-test-utils.path = "../ontol-test-utils"
ontol-examples.path = "../ontol-examples"
#serde_json.workspace = true
tracing-subscriber.workspace = true
#unimock.workspace = true
assert_matches = "1"
pretty_assertions = "1"
#serde-value = "0.7"
#rstest.workspace = true
