[package]
name = "ontol-runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false

[dependencies]
ontol-macros.path = "../ontol-macros"
tracing.workspace = true
serde = { workspace = true, features = ["derive", "rc"] }
serde_json.workspace = true
fnv.workspace = true
uuid.workspace = true
ulid = { workspace = true, features = ["serde"] }
chrono.workspace = true
bitflags.workspace = true
bit-set.workspace = true
thin-vec.workspace = true
regex-automata.workspace = true
arcstr.workspace = true
ordered-float.workspace = true
itertools.workspace = true
postcard.workspace = true
indexmap = { workspace = true, features = ["serde"] }
smallvec = { workspace = true, features = ["serde"] }
smartstring = { version = "1", features = ["serde"] }
num = { version = "0.4", features = ["serde"] }
serde-value = "0.7"
urlencoding = "2"
bit-vec = { version = "0.8", features = ["serde"] }
thiserror = "1"
ahash = "0.8"
phf_shared = "0.11"
num_enum = { version = "0.7", default-features = false }
hex = "0.4"
base64 = "0.22"

[dev-dependencies]
tracing-subscriber.workspace = true
pretty_assertions = "1"
