[package]
name = "ontol-runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false

[dependencies]
ontol-macros.path = "../ontol-macros"

arcstr.workspace = true
bit-set.workspace = true
bitflags.workspace = true
chrono.workspace = true
fnv.workspace = true
itertools.workspace = true
ordered-float.workspace = true
postcard.workspace = true
regex-automata.workspace = true
serde = { workspace = true, features = ["derive", "rc"] }
serde_json.workspace = true
thin-vec.workspace = true
tracing.workspace = true
ulid = { workspace = true, features = ["serde"] }
uuid.workspace = true

ahash = "0.8"
bit-vec = { version = "0.8", features = ["serde"] }
base64 = "0.22"
hex = "0.4"
indexmap = { workspace = true, features = ["serde"] }
num = { version = "0.4", features = ["serde"] }
num_enum = { version = "0.7", default-features = false }
phf_shared = "0.11"
serde-value = "0.7"
smallvec = { workspace = true, features = ["serde"] }
compact_str = { version = "0.8", features = ["serde"] }
thiserror = "1"
urlencoding = "2"

[dev-dependencies]
tracing-subscriber.workspace = true
pretty_assertions = "1"
