[package]
name = "ontol-lsp-wasm"
version = "0.4.0"
edition = "2021"

[dependencies]
ontol-lsp = { path = "../ontol-lsp", features = ["wasm"] }
tokio = { version = "1", features = ["io-std", "rt-multi-thread", "macros"]}
tower-lsp = "0.20"
tracing.workspace = true
tracing-subscriber.workspace = true
