[package]
name = "ontol-parser"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
logos = "0.14"
unindent = "0.2"
thin-vec.workspace = true
bitflags.workspace = true

[dev-dependencies]
assert_matches = "1"
indoc = "2"
pretty_assertions = "1"
rstest.workspace = true
