[package]
name = "ontol-parser"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
ontol-core.path = "../ontol-core"
bitflags.workspace = true
fnv.workspace = true
logos = "0.15"
serde = { version = "1", features = ["derive"] }
thin-vec.workspace = true
tracing = "0.1"
ulid.workspace = true
unindent = "0.2"

[dev-dependencies]
assert_matches = "1"
indoc = "2"
pretty_assertions = "1"
rstest.workspace = true
