[package]
name = "ontol-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false

[dependencies]
logos = "0.14"
unindent = "0.2"
thin-vec.workspace = true

[dev-dependencies]
assert_matches = "1"
indoc = "2"
pretty_assertions = "1"
rstest = { version = "0.19", default-features = false }
