[package]
name = "ontol-compiler"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
ontol-macros.path = "../ontol-macros"
ontol-hir.path = "../ontol-hir"
ontol-runtime.path = "../ontol-runtime"
ontol-parser.path = "../ontol-parser"
async-trait.workspace = true
fnv.workspace = true
indexmap.workspace = true
serde.workspace = true
smallvec.workspace = true
tracing.workspace = true
bit-set.workspace = true
thin-vec.workspace = true
regex-automata.workspace = true
arcstr.workspace = true
bitflags.workspace = true
ordered-float.workspace = true
itertools.workspace = true
ena = "0.14"
bumpalo = "3"
regex-syntax = "0.8"
patricia_tree = "0.9"
heck = "0.5"
phf_shared = "0.11"
phf_generator = "0.11"
indoc = "2"
displaydoc = "0.2"
ulid = "1"
url = "2"

[dev-dependencies]
ontol-test-utils.path = "../ontol-test-utils"
ontol-examples.path = "../ontol-examples"
serde_json.workspace = true
tracing-subscriber.workspace = true
unimock.workspace = true
assert_matches = "1"
pretty_assertions = "1"
serde-value = "0.7"
rstest.workspace = true
