[package]
name = "ontol-compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false

[dependencies]
ontol-macros.path = "../ontol-macros"
ontol-hir.path = "../ontol-hir"
ontol-runtime.path = "../ontol-runtime"
ontol-parser.path = "../ontol-parser"
fnv.workspace = true
indexmap.workspace = true
serde.workspace = true
smallvec.workspace = true
thiserror.workspace = true
tracing.workspace = true
either.workspace = true
bit-set.workspace = true
thin-vec.workspace = true
regex-automata.workspace = true
arcstr.workspace = true
bitflags.workspace = true
ordered-float.workspace = true
ena = "0.14"
bumpalo = "3"
regex-syntax = "0.8"
patricia_tree = "0.8"
heck = "0.5"
phf_shared = "0.11"
phf_generator = "0.11"
indoc = "2"

[dev-dependencies]
ontol-test-utils.path = "../ontol-test-utils"
serde_json.workspace = true
tracing-subscriber.workspace = true
unimock.workspace = true
assert_matches = "1"
pretty_assertions = "1"
serde-value = "0.7"
rstest = { version = "0.19", default-features = false }
