<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>on</string>
	</array>
	<key>name</key>
	<string>ONTOL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>use declaration</string>
			<key>match</key>
			<string>^(use)</string>
			<key>name</key>
			<string>keyword.import.ontol</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>use as declaration</string>
			<key>match</key>
			<string>\s(as)\s</string>
			<key>name</key>
			<string>keyword.import.as.ontol</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>pub export modifier</string>
			<key>match</key>
			<string>^(pub)</string>
			<key>name</key>
			<string>storage.modifier.pub.ontol</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>type declaration</string>
			<key>match</key>
			<string>\b(type)</string>
			<key>name</key>
			<string>keyword.declaration.type.ontol</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>with context block</string>
			<key>match</key>
			<string>^(with)</string>
			<key>name</key>
			<string>keyword.context.block.with.ontol</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>rel declaration</string>
			<key>match</key>
			<string>\b(rel)</string>
			<key>name</key>
			<string>keyword.declaration.rel.ontol</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>fmt expression</string>
			<key>match</key>
			<string>\b(fmt)</string>
			<key>name</key>
			<string>keyword.declaration.fmt.ontol</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>fat arrow (fmt expression)</string>
			<key>match</key>
			<string>(=&gt;)</string>
			<key>name</key>
			<string>keyword.operator.fatarrow.ontol</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.declaration.map.ontol</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.ontol</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>map declaration</string>
			<key>match</key>
			<string>\b(map)\s*(\()(.*)(\))</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>built-in types</string>
			<key>match</key>
			<string>\b(bool|int|float|number|string|datetime|date|time|uuid|regex|array|seq|map|fn)</string>
			<key>name</key>
			<string>storage.type.ontol</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>number literal</string>
			<key>match</key>
			<string>(\d+(\.?\d+)*)</string>
			<key>name</key>
			<string>constant.numeric.ontol</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>built-in constant value</string>
			<key>match</key>
			<string>\b(true|false|null|inf|nan)\b</string>
			<key>name</key>
			<string>constant.language.ontol</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>built-in assigment keywords</string>
			<key>match</key>
			<string>\b(is|identifies)\b</string>
			<key>name</key>
			<string>variable.function.ontol</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>unit/self underscore</string>
			<key>match</key>
			<string>\s(_)\s</string>
			<key>name</key>
			<string>variable.language.ontol</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\'</string>
			<key>comment</key>
			<string>single quoted string literal</string>
			<key>end</key>
			<string>\'</string>
			<key>name</key>
			<string>string.quoted.single.ontol</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escaped_char</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>comment</key>
			<string>double quoted string literal</string>
			<key>end</key>
			<string>\"</string>
			<key>name</key>
			<string>string.quoted.double.ontol</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escaped_char</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>/[^/\s]</string>
			<key>comment</key>
			<string>regex literal</string>
			<key>end</key>
			<string>[^\\]/</string>
			<key>name</key>
			<string>string.regexp.ontol</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>//[^/]</string>
			<key>comment</key>
			<string>comment</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.line.double-slash.ontol</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^///</string>
			<key>comment</key>
			<string>doc comment</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.block.documentation.ontol</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>sigil</string>
			<key>match</key>
			<string>[.,:?+*=]+</string>
			<key>name</key>
			<string>keyword.operator.ontol</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>special case sigil</string>
			<key>match</key>
			<string>[^\w\s][&lt;&gt;_-]+[^\w\s]</string>
			<key>name</key>
			<string>keyword.operator.ontol</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>escaped_char</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\\\</string>
					<key>name</key>
					<string>constant.character.escape.backslash.ontol</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\/</string>
					<key>name</key>
					<string>constant.character.escape.slash.ontol</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\'</string>
					<key>name</key>
					<string>constant.character.escape.single-quote.ontol</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\"</string>
					<key>name</key>
					<string>constant.character.escape.double-quote.ontol</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\b</string>
					<key>name</key>
					<string>constant.character.escape.backspace.ontol</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\f</string>
					<key>name</key>
					<string>constant.character.escape.formfeed.ontol</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\n</string>
					<key>name</key>
					<string>constant.character.escape.newline.ontol</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\c|\\r</string>
					<key>name</key>
					<string>constant.character.escape.carriagereturn.ontol</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\l</string>
					<key>name</key>
					<string>constant.character.escape.linefeed.ontol</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\t</string>
					<key>name</key>
					<string>constant.character.escape.tabulator.ontol</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.ontol</string>
	<key>uuid</key>
	<string>4fc14b00-3ee2-4804-9036-e70090594121</string>
</dict>
</plist>
