[package]
name = "domain-engine-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false

[dependencies]
ontol-runtime.path = "../../ontol/ontol-runtime"
smartstring.workspace = true
thiserror.workspace = true
tracing.workspace = true
indexmap.workspace = true
fnv.workspace = true
itertools.workspace = true
uuid = { workspace = true, features = ["v4", "v7"] }
async-trait.workspace = true
chrono.workspace = true
smallvec.workspace = true
bit-set.workspace = true
thin-vec.workspace = true
ordered-float.workspace = true
unimock.workspace = true
serde = "1"
serde_json = "1"
anyhow = "1"

[dev-dependencies]
ontol-test-utils.path = "../../ontol/ontol-test-utils"
domain-engine-test-utils.path = "../domain-engine-test-utils"
test-log.workspace = true
tracing-subscriber.workspace = true
pretty_assertions = "1"
