[package]
name = "domain-engine-juniper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false

[dependencies]
ontol-runtime.path = "../ontol-runtime"
domain-engine-core.path = "../domain-engine-core"
juniper = { git = "https://github.com/protojour/juniper", branch = "protojour-mods", default-features = false, features = ["schema-language"] }
tracing = "0.1"
serde = "1"
serde_json = "1"
smartstring = { version = "1", features = ["serde"] }
indexmap = { version = "1", features = ["serde"] }
fnv = "1"
convert_case = "0.6"

[dev-dependencies]
ontol-test-utils.path = "../ontol-test-utils"
tracing-subscriber = {version = "0.3", default-features = false, features = ["env-filter", "fmt"]}
test-log = { version = "0.2", default-features = false, features = ["trace"] }
tokio = { version = "1", features = ["macros", "rt"] }
async-trait = "0.1"
pretty_assertions = "1"
