[package]
name = "ontol-syntax"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
ontol-core.path = "../ontol-core"
ontol-parser.path = "../ontol-parser"
rowan = "0.16"

[dev-dependencies]
pretty_assertions = "1"
