[package]
name = "ontol-test-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false

[features]
validate-jsonschema = ["dep:jsonschema"]

[dependencies]
ontol-compiler.path = "../ontol-compiler"
ontol-parser.path = "../ontol-parser"
ontol-runtime.path = "../ontol-runtime"
ontol-faker.path = "../ontol-faker"
arcstr.workspace = true
tracing.workspace = true
pretty_assertions = "1"
serde.workspace = true
serde_json.workspace = true
fnv.workspace = true
unimock.workspace = true
jsonschema = { version = "0.20", optional = true, default-features = false, features = ["draft202012"] }
serde-value = "0.7"
url = "2"
