[package]
name = "ontol-test-utils"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[features]
validate-jsonschema = ["dep:jsonschema"]

[dependencies]
ontol-compiler.path = "../ontol-compiler"
ontol-parser.path = "../ontol-parser"
ontol-runtime.path = "../ontol-runtime"
ontol-faker.path = "../ontol-faker"
tracing.workspace = true
pretty_assertions = "1"
serde.workspace = true
serde_json.workspace = true
fnv.workspace = true
unimock.workspace = true
jsonschema = { version = "0.29", optional = true, default-features = false }
serde-value = "0.7"
url = "2"
