[package]
name = "ontol-faker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false

[features]
js = ["getrandom/js"]

[dependencies]
ontol-runtime.path = "../ontol-runtime"
tracing.workspace = true
smallvec.workspace = true
uuid = { workspace = true, features = ["fast-rng"] }
fake = { version = "2", features = ["chrono"] }
rand = { version = "0.8", features = ["std_rng"] }
regex_generate = "0.2"
getrandom = { version = "0.2" }

[dev-dependencies]
