[package]
name = "ontol-faker"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false

[features]
js = ["getrandom_02/js", "getrandom/wasm_js"]

[dependencies]
ontol-runtime.path = "../ontol-runtime"
tracing.workspace = true
smallvec.workspace = true
uuid = { workspace = true, features = ["fast-rng"] }
ulid.workspace = true
fake = { version = "4", features = ["chrono"] }
rand_08 = { package = "rand", version = "0.8", features = ["std_rng"] }
rand = { version = "0.9", features = ["std_rng"] }
regex_generate = "0.2"
getrandom_02 = { package = "getrandom", version = "0.2" }
getrandom = { version = "0.3" }

[dev-dependencies]
