[package]
name = "ontol-lsp"
version = "0.4.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false

[features]
wasm = []

[dependencies]
ontol-runtime.path = "../ontol-runtime"
ontol-compiler.path = "../ontol-compiler"
ontol-parser.path = "../ontol-parser"
logos = "0.14"
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["fs", "io-std", "io-util", "rt-multi-thread", "macros"]}
tower-lsp = { version = "0.20" }
