[package]
name = "ontol-lsp"
version = "0.4.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false

[features]
wasm = []

[dependencies]
ontol-runtime.path = "../ontol-runtime"
ontol-compiler.path = "../ontol-compiler"
ontol-parser.path = "../ontol-parser"
serde.workspace = true
serde_json.workspace = true
tokio = { version = "1", features = ["io-std", "rt-multi-thread", "sync", "macros"]}
tower-lsp = "0.20"
