[package]
name = "ontol-lsp"
version = "0.4.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false

[features]
wasm = []

[dependencies]
ontol-runtime.path = "../ontol-runtime"
ontol-compiler.path = "../ontol-compiler"
ontol-core.path = "../ontol-core"
ontol-parser.path = "../ontol-parser"
serde.workspace = true
serde_json.workspace = true
tokio = { version = "1", features = ["io-std", "rt-multi-thread", "sync", "macros"]}
tower-lsp = "0.20"
tracing.workspace = true
lazy-regex = { version = "3.3.0", default-features = false, features = ["lite"] }
indoc = "2"
