[package]
name = "ontol-lsp"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false

[features]
wasm = []

[dependencies]
ontol-runtime.path = "../ontol-runtime"
ontol-compiler.path = "../ontol-compiler"
ontol-parser.path = "../ontol-parser"
chumsky.workspace = true
either.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
lsp-types = "0.94.0"
regex = "1.9.1"
substring = "1.4.5"
tower-lsp = { version = "0.20.0" }
futures-util = { version = "0.3.28", features = ["futures-io", "io"] }
derivative = "2"
