[package]
name = "ontol-compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false

[dependencies]
ontol-runtime.path = "../ontol-runtime"
ontol-parser.path = "../ontol-parser"
tracing.workspace = true
smartstring.workspace = true
indexmap.workspace = true
fnv.workspace = true
chumsky = "0.9"
smallvec = "1"
fraction = "0.13"
ena = "0.14"
bumpalo = "3"
thiserror = "1"
miette = "5"
regex-syntax = "0.6"
regex = "1"
patricia_tree = "0.5"

[dev-dependencies]
ontol-test-utils.path = "../ontol-test-utils"
assert_matches = "1"
pretty_assertions = "1"
serde_json.workspace = true
tracing-subscriber = {version = "0.3", default-features = false, features = ["env-filter", "fmt"]}
test-log = { version = "0.2", default-features = false, features = ["trace"] }
