[package]
name = "ontol-compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false

[dependencies]
ontol-runtime.path = "../ontol-runtime"
ontol-parser.path = "../ontol-parser"
ontos.path = "../ontos"
tracing.workspace = true
smartstring.workspace = true
indexmap.workspace = true
fnv.workspace = true
chumsky = "0.9"
smallvec = "1"
fraction = "0.13"
ena = "0.14"
bumpalo = "3"
thiserror = "1"
regex-syntax = "0.6"
regex = "1"
patricia_tree = "0.5"
bit-set = "0.5"
derive-debug-extras = { version = "0.2", features = ["auto-debug-single-tuple-inline"] }

[dev-dependencies]
ontol-test-utils.path = "../ontol-test-utils"
serde_json.workspace = true
tracing-subscriber.workspace = true
test-log.workspace = true
assert_matches = "1"
pretty_assertions = "1"
indoc = "2"
