[package]
name = "ontool"
version = "0.3.0"
edition = "2021"

[dependencies]
domain-engine-juniper.path = "../domain-engine-juniper"
ontol-compiler.path = "../ontol-compiler"
ontol-parser.path = "../ontol-parser"
ontol-runtime.path = "../ontol-runtime"
ontol-lsp.path = "../ontol-lsp"
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
clap.workspace = true
bincode.workspace = true
ariadne = { version = "0.3.0", features = ["auto-color"] }
tower-lsp = "0.20.0"
tokio = { workspace = true, features = ["full"] }

[[bin]]
name = "ontool"
path = "src/main.rs"
