[package]
name = "ontol-tests"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
ontol-runtime = { path = "../ontol-runtime" }
ontol-compiler = { path = "../ontol-compiler" }
assert_matches = "1"
pretty_assertions = "1"
serde = "1"
serde_json = "1"
