[book]
title = "ONTOL Documentation"
authors = ["Protojour dev team <devs@protojour.com>"]
language = "en"
multilingual = false
src = "src"

[preprocessor.ontol-documentation]
command = "cargo run -p ontol-documentation-preprocessor"
renderers = ["html"]

[preprocessor.index]
renderers = ["html"]

[preprocessor.links]
renderers = ["html"]

[output.html]
additional-js = [
    "theme/highlight-ontol.js",
    "theme/highlight-graphql.js"
]
