name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-targets

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        ports:
        - 5432:5432
        env:
          POSTGRES_DB: domainengine
          POSTGRES_USER: domainengine
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: test
        env:
          DOMAIN_ENGINE_TEST_PG_HOST: localhost
          DOMAIN_ENGINE_SKIP_ARANGO_TESTS: "1"
        run: cargo test --all --tests --benches
